### ISSUE TITLE
Remove node_modules from Git Repository

### ISSUE THREAD

**Issue by FREDVUNI** [NambiLucia/Quote-API#3]
**Steps to Remove `node_modules`:**

1. **Remove `node_modules` from Git:**

   ```bash
   git rm -r --cached node_modules
   ```

2. **Update `.gitignore`:**

   Add `node_modules/` to the `.gitignore` file:

   ```bash
   node_modules/
   ```

3. **Commit Changes:**

   ```bash
   git add .gitignore
   git commit -m "Remove node_modules and add to .gitignore"
   ```

4. **Push Changes:**

   ```bash
   git push origin [branch-name]
   ```

**Why This Is Important:**

- Reduces repository size and improves performance.
- Ensures developers use the latest dependencies.

**Comment by NambiLucia** [comment]
## Done. Thanks! @FREDVUNI

**Comment by NambiLucia** [comment]
Done. Thanks! @FREDVUNI
